In [1]:
import pandas as pd
import numpy as np

In [7]:
np.random.randn(9)

array([-1.05695882,  0.95387081,  1.10617   ,  1.02573861,  1.29766183,
       -0.98632358,  0.50359122, -0.88419185,  0.2411845 ])

In [39]:
np.random.seed(10)
np.random.rand(8)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071])

In [34]:
np.random.rand(8)

array([0.0202184 , 0.83261985, 0.77815675, 0.87001215, 0.97861834,
       0.79915856, 0.46147936, 0.78052918])

In [42]:
np.random.seed(10)
np.random.permutation(10)

array([8, 2, 5, 6, 3, 1, 0, 7, 4, 9])

In [46]:
np.random.permutation(10)

array([2, 0, 9, 5, 4, 1, 7, 8, 6, 3])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
pd.Series(np.random.randn(9),index=[['a','a','a','b','b','c','c','d','d'],
                         [1,2,3,1,3,1,2,2,3]])

a  1   -0.590913
   2    0.389363
   3   -0.526996
b  1   -0.514308
   3    0.897609
c  1    0.989252
   2    0.259225
d  2   -0.024193
   3    0.358497
dtype: float64

In [51]:
data = pd.Series(np.random.randn(9),index=[['a','a','a','b','b','c','c','d','d'],
                         [1,2,3,1,3,1,2,2,3]])

In [52]:
# to see the index names
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [53]:
data['b'] 

1    1.707755
3   -1.967117
dtype: float64

In [54]:
data['b':'c'] 

b  1    1.707755
   3   -1.967117
c  1   -0.870957
   2   -1.106825
dtype: float64

In [56]:
data['a'] + data['b']

1    1.330209
2         NaN
3   -0.942273
dtype: float64

In [75]:
# selection on an inner portion
# get all the 2's together from all letters
data.loc[:,2]

a    0.695631
c   -1.106825
d    0.275124
dtype: float64

In [76]:
# can unstack the data as well
data.unstack()

1         2         3
a -0.377546  0.695631  1.024845
b  1.707755       NaN -1.967117
c -0.870957 -1.106825       NaN
d       NaN  0.275124 -0.364456

In [78]:
data.unstack().stack()

a  1   -0.377546
   2    0.695631
   3    1.024845
b  1    1.707755
   3   -1.967117
c  1   -0.870957
   2   -1.106825
d  2    0.275124
   3   -0.364456
dtype: float64

In [101]:
pd.DataFrame(np.arange(12).reshape(4,3),
          index=[['a','a','b','b'],[1,2,1,2]],
         columns=[['Ohio','Ohio','Colorado'],['Green','Red','Blue']])

Ohio     Colorado
    Green Red     Blue
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [102]:
frame = pd.DataFrame(np.arange(12).reshape(4,3),
          index=[['a','a','b','b'],[1,2,1,2]],
         columns=[['Ohio','Ohio','Colorado'],['Green','Red','Blue']])

In [110]:
# you can set index names and column names too
frame.columns.names =['state','color']
frame.index.names = ['key1','key2']

In [111]:
frame

state      Ohio     Colorado
color     Green Red     Blue
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [150]:
frame[2:]['Colorado']

color      Blue
key1 key2      
b    1        8
     2       11

In [164]:
pd.DataFrame(frame[:2]['Ohio']['Red'])

Red
key1 key2     
a    1       1
     2       4

In [165]:
frame

state      Ohio     Colorado
color     Green Red     Blue
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [168]:
# switch indexes
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red     Blue
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [324]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red     Blue
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [334]:
# move Colorado to first position
frame.reindex(sorted(frame.columns),axis=1)

state     Colorado  Ohio    
color         Blue Green Red
key1 key2                   
a    1           2     0   1
     2           5     3   4
b    1           8     6   7
     2          11     9  10

In [349]:
# move Colorado to first position (alternative way)
columns = pd.Index([('Colorado','Blue'),('Ohio','Green'),('Ohio','Red')])
pd.DataFrame(frame, columns=columns)

Colorado  Ohio    
              Blue Green Red
key1 key2                   
a    1           2     0   1
     2           5     3   4
b    1           8     6   7
     2          11     9  10

In [354]:
pd.DataFrame(frame.swaplevel('key2','key1'), columns=columns)

Colorado  Ohio    
              Blue Green Red
key2 key1                   
1    a           2     0   1
2    a           5     3   4
1    b           8     6   7
2    b          11     9  10

In [378]:
frame.rename(columns={'Colorado':'California','Green':'Purple'})

state       Ohio     California
color     Purple Red       Blue
key1 key2                      
a    1         0   1          2
     2         3   4          5
b    1         6   7          8
     2         9  10         11

In [270]:
data1 = pd.DataFrame([[1,2,3,4,2],[5,5,5,5,5],[4323,4323,1231,5434,23432]],columns=['A','B','C','D','E'])

In [271]:
data1

A     B     C     D      E
0     1     2     3     4      2
1     5     5     5     5      5
2  4323  4323  1231  5434  23432

In [272]:
cols = list(data1)

In [273]:
cols.insert(0,cols.pop(cols.index('B')))
for i in range(1):
    cols.pop()

In [274]:
data1 = data1.reindex(columns = cols)

In [275]:
data1

B     A     C     D
0     2     1     3     4
1     5     5     5     5
2  4323  4323  1231  5434

In [414]:
# sum by column (axis=0) or row (axis=1)
pd.DataFrame(data1.sum(axis=1))

0
0     10
1     20
2  15311

In [415]:
frame

state      Ohio     Colorado
color     Green Red     Blue
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [416]:
frame.sum(level='key1')

state  Ohio     Colorado
color Green Red     Blue
key1                    
a         3   5        7
b        15  17       19

In [421]:
pd.DataFrame(frame.sum(axis=0)).T

state  Ohio     Colorado
color Green Red     Blue
0        18  22       26

In [422]:
frame

state      Ohio     Colorado
color     Green Red     Blue
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [427]:
df1 = pd.DataFrame({'key':['b','b','a','c','a','a','b'],
             'data1':range(7)})
df2 = pd.DataFrame({'key':['a','b','d'],
                   'data2':range(3)})

In [428]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [429]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [430]:
pd.merge(df1,df2,on='key',how='left')

key  data1  data2
0   b      0    1.0
1   b      1    1.0
2   a      2    0.0
3   c      3    NaN
4   a      4    0.0
5   a      5    0.0
6   b      6    1.0

In [437]:
left = pd.DataFrame({'key1':['foo','gabe','foo'],
             'key2':['one','two','one'],
             'lval':[1,2,3]})
right = pd.DataFrame({'key1':['gabe','foo','gabe','gabe'],
             'key2':['one','two','one','two'],
             'rval':[4,5,6,7]})


In [438]:
left

key1 key2  lval
0   foo  one     1
1  gabe  two     2
2   foo  one     3

In [439]:
right

key1 key2  rval
0  gabe  one     4
1   foo  two     5
2  gabe  one     6
3  gabe  two     7

In [443]:
# this is like an inner join (only what's shared between key1 and key2)
pd.merge(left,right, on=['key1','key2'])

key1 key2  lval  rval
0  gabe  two     2     7

In [444]:
# an outer join would be (to give all the combinations of key1 and key2)
pd.merge(left,right,on=['key1','key2'],how='outer')

key1 key2  lval  rval
0   foo  one   1.0   NaN
1   foo  one   3.0   NaN
2  gabe  two   2.0   7.0
3  gabe  one   NaN   4.0
4  gabe  one   NaN   6.0
5   foo  two   NaN   5.0

In [447]:
# then you can also add names for clarity
pd.merge(left,right,on=['key1'],suffixes=('_left_data_set','_right_data_set'))

key1 key2_left_data_set  lval key2_right_data_set  rval
0   foo                one     1                 two     5
1   foo                one     3                 two     5
2  gabe                two     2                 one     4
3  gabe                two     2                 one     6
4  gabe                two     2                 two     7

In [473]:
# to merge a dataset with a key, and another without a key (but similar index)
left1 = pd.DataFrame({'key':['a','b','a','a','b','c'],
                     'value': range(6)})
right1 = pd.DataFrame({'group_val':[3.5,7]},
                     index=['a','b'])

TypeError: 'dict' object is not callable

In [451]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [452]:
right1

group_val
a        3.5
b        7.0

In [459]:
pd.merge(left1,right1,left_on='key',right_index=True,how='outer') #specify outer to get the full set

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [4]:
left2 = pd.DataFrame({'key1':['gabe','aj','gabe','kaylee','gabe'],'values':range(5)})
right2 = pd.DataFrame({'vals':[23,41]},index=['gabe','kaylee'])

In [5]:
left2

key1  values
0    gabe       0
1      aj       1
2    gabe       2
3  kaylee       3
4    gabe       4

In [6]:
right2

vals
gabe      23
kaylee    41

In [7]:
pd.merge(left2,right2,left_on='key1',right_index=True,how='outer')

key1  values  vals
0    gabe       0  23.0
2    gabe       2  23.0
4    gabe       4  23.0
1      aj       1   NaN
3  kaylee       3  41.0

In [17]:
lefth = pd.DataFrame({'key1':['Ohio','Ohio','Ohio','Nevada','Nevada'],
             'key2':[2000,2001,2002,2001,2002],
             'data':np.arange(5.0)})

In [19]:
righth = pd.DataFrame(np.arange(12).reshape(6,2),
            index=[['Nevada','Nevada','Ohio','Ohio','Ohio','Ohio'],
                   [2001,2000,2000,2000,2001,2002]],
            columns=['event1','event2'])

In [20]:
lefth

key1  key2  data
0    Ohio  2000   0.0
1    Ohio  2001   1.0
2    Ohio  2002   2.0
3  Nevada  2001   3.0
4  Nevada  2002   4.0

In [21]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [26]:
# to merge righth (which has two indices) you'll have to include both key1 and key2 in the left_on statement
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True,how='outer')

key1  key2  data  event1  event2
0    Ohio  2000   0.0     4.0     5.0
0    Ohio  2000   0.0     6.0     7.0
1    Ohio  2001   1.0     8.0     9.0
2    Ohio  2002   2.0    10.0    11.0
3  Nevada  2001   3.0     0.0     1.0
4  Nevada  2002   4.0     NaN     NaN
4  Nevada  2000   NaN     2.0     3.0

In [40]:
state1 = pd.DataFrame(np.arange(6).reshape(3,2), 
                index=['a','c','e'],
             columns=['Ohio','Nevada'])
state2 = pd.DataFrame(np.arange(8).reshape(4,2),
index=['b','c','d','e'],
columns=['Missouri','Alabama'])

In [43]:
pd.concat([state1,state2],axis=1) ### here's a concat to join them

Ohio  Nevada  Missouri  Alabama
a   0.0     1.0       NaN      NaN
c   2.0     3.0       2.0      3.0
e   4.0     5.0       6.0      7.0
b   NaN     NaN       0.0      1.0
d   NaN     NaN       4.0      5.0

In [51]:
state1.join(state2,how='outer') ### here's a join to join them

Ohio  Nevada  Missouri  Alabama
a   0.0     1.0       NaN      NaN
b   NaN     NaN       0.0      1.0
c   2.0     3.0       2.0      3.0
d   NaN     NaN       4.0      5.0
e   4.0     5.0       6.0      7.0

In [50]:
pd.merge(state1,state2,how='outer',left_index=True,right_index=True) ### here's the merge that will join them

Ohio  Nevada  Missouri  Alabama
a   0.0     1.0       NaN      NaN
b   NaN     NaN       0.0      1.0
c   2.0     3.0       2.0      3.0
d   NaN     NaN       4.0      5.0
e   4.0     5.0       6.0      7.0

In [61]:
another = pd.DataFrame(np.arange(10).reshape(5,2), index=['a','b','c','d','e'], columns=['New York','Minnesota'])

In [62]:
another.join(state2,how='outer')

New York  Minnesota  Missouri  Alabama
a         0          1       NaN      NaN
b         2          3       0.0      1.0
c         4          5       2.0      3.0
d         6          7       4.0      5.0
e         8          9       6.0      7.0

In [66]:
pd.concat([state2,another],axis=1)

Missouri  Alabama  New York  Minnesota
b       0.0      1.0         2          3
c       2.0      3.0         4          5
d       4.0      5.0         6          7
e       6.0      7.0         8          9
a       NaN      NaN         0          1

In [64]:
pd.merge(state2,another,left_index=True,right_index=True,how='outer')

Missouri  Alabama  New York  Minnesota
a       NaN      NaN         0          1
b       0.0      1.0         2          3
c       2.0      3.0         4          5
d       4.0      5.0         6          7
e       6.0      7.0         8          9

In [67]:
s1 = pd.Series([0,1],index=['a','b'])
s2 = pd.Series([2,3,4],index=['c','d','e'])
s3 = pd.Series([5,6],index=['f','g'])

In [69]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [72]:
s4 = pd.concat([s1,s3])

In [73]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [78]:
pd.concat([s1,s2,s4], keys=['one','two','three'])

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  a    0
       b    1
       f    5
       g    6
dtype: int64

In [79]:
pd.concat([s1,s2,s4], keys=['one','two','three'],axis=1) #if you change the axis=1, you can make them column headers

one  two  three
a  0.0  NaN    0.0
b  1.0  NaN    1.0
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [81]:
s1

a    0
b    1
dtype: int64

In [82]:
s2

c    2
d    3
e    4
dtype: int64

In [95]:
pd.concat([s1,s2],axis=1,keys=['Gabe','Kaylee'])

Gabe  Kaylee
a   0.0     NaN
b   1.0     NaN
c   NaN     2.0
d   NaN     3.0
e   NaN     4.0

In [101]:
a = pd.Series([np.nan,2.5,0.0,3.5,4.5,np.nan],
         index=['f','e','d','c','b','a'])
b = pd.Series([0.,np.nan,2.,np.nan,np.nan,5.],
         index=['a','b','c','d','e','f'])

In [102]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [103]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [105]:
pd.concat([a,b],axis=1)

0    1
f  NaN  5.0
e  2.5  NaN
d  0.0  NaN
c  3.5  2.0
b  4.5  NaN
a  NaN  0.0

In [106]:
# to "patch" missing data with values from another data set, use combine_first
b.combine_first(a)

a    0.0
b    4.5
c    2.0
d    0.0
e    2.5
f    5.0
dtype: float64

In [119]:
data = pd.DataFrame(np.arange(6).reshape(2,3),
            columns=pd.Index(['one','two','three'],name='number'),
            index=pd.Index(['Ohio','Colorado'],name='state'))

In [120]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [122]:
pd.DataFrame(data.stack())

0
state    number   
Ohio     one     0
         two     1
         three   2
Colorado one     3
         two     4
         three   5

In [133]:
pd.DataFrame(data.unstack('state')) # allows you to swap the inner and outer indices

0
number state      
one    Ohio      0
       Colorado  3
two    Ohio      1
       Colorado  4
three  Ohio      2
       Colorado  5

In [137]:
s1 = pd.Series([0,1,2,3],index=['a','b','c','d'])
s2 = pd.Series([4,5,6],index=['c','d','e'])

In [140]:
data2 = pd.concat([s1,s2],keys=['one','two'])

In [141]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [143]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [147]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [145]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [225]:
pd.concat([left,right],axis=1)

left  right
0     0      5
1     1      6
2     2      7
3     3      8
4     4      9
5     5     10

In [216]:
right = pd.DataFrame(np.arange(5,11).reshape(6,1),columns=['right'])
left = pd.DataFrame(np.arange(6).reshape(6,1),columns=['left'])

In [237]:
pd.DataFrame([0,1,2],index=[['Ohio','Ohio','Ohio'],['one','two','three']],columns=['left'])

left
Ohio one       0
     two       1
     three     2

In [253]:
pd.DataFrame([[0,5],[1,6],[2,7]],index=[['Ohio','Ohio','Ohio'],['one','two','three']],columns=['left','right'])

left  right
Ohio one       0      5
     two       1      6
     three     2      7

In [284]:
pd.DataFrame([[3,8],[4,9],[5,10]],
             index=[['Colorado','Colorado','Colorado'],['one','two','three']],
             columns=['left','right'])

left  right
Colorado one       3      8
         two       4      9
         three     5     10

In [271]:
one = pd.DataFrame([[0,5],[1,6],[2,7]],index=[['Ohio','Ohio','Ohio'],['one','two','three']],columns=['left','right'])
two = pd.DataFrame([[3,8],[4,9],[5,10]],index=[['Colorado','Colorado','Colorado'],['one','two','three']],columns=['left','right'])

In [300]:
pd.DataFrame(np.arange(6).reshape(2,3),
             index=pd.Index(['Ohio','Colorado'],name='state'),
             columns=pd.Index(['one','two','three'],name='number')).stack()

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [301]:
one = pd.DataFrame(np.arange(6).reshape(2,3),
             index=pd.Index(['Ohio','Colorado'],name='state'),
             columns=pd.Index(['one','two','three'],name='number')).stack()

In [309]:
pd.DataFrame({'left':one,'right':one+5})

left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [310]:
pd.DataFrame({'left':one,'right':one+5},
            columns=pd.Index(['left','right'],name='side'))

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [317]:
new = pd.DataFrame({'left':one,'right':one+5},
            columns=pd.Index(['left','right'],name='side'))
new.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [318]:
new.unstack('state').stack('side')

state         Colorado  Ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7