In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[-0.40706287,  1.36123138, -0.12085486],
       [-0.6950071 , -1.13406762,  0.72599961]])

In [16]:
data1 = np.random.randn(1,5) #normal distribution
data2 = np.random.rand(1,5)  #between 0 and 1

In [18]:
data1

array([[ 0.00707238,  0.26862163,  0.8882745 , -1.18891274,  0.183924  ]])

In [19]:
data2

array([[0.17752422, 0.03513974, 0.31898646, 0.03845678, 0.23665895]])

In [28]:
data1 = [6, 7.5, 8, 0, 1]

In [29]:
data1

[6, 7.5, 8, 0, 1]

In [30]:
arr1 = np.array(data1)

In [31]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [52]:
old_values_arr3 = arr3.copy()

In [53]:
arr3[2] = 35

In [54]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [35, 35, 35]])

In [56]:
old_values_arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
names = np.array(['Gabe', 'Kaylee', 'Jim'])

In [61]:
names[1]

'Kaylee'

In [65]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [35, 35, 35]])

In [68]:
arr3.reshape((1,9)).sort()

In [72]:
arr3[2] = 0

In [73]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [104]:
arr3.reshape(1,9)

array([[0, 0, 0, 1, 2, 3, 4, 5, 6]])

In [119]:
np.sort(arr3.reshape(1,9))[::-1]

array([[0, 0, 0, 1, 2, 3, 4, 5, 6]])

In [129]:
-np.sort(-arr3.reshape(1,9))

array([[6, 5, 4, 3, 2, 1, 0, 0, 0]])