In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [3]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.random.rand(1)

array([0.95960997])

In [21]:
np.random.randint(10)

2

In [26]:
np.random.randint(0,10)

8

In [32]:
np.random.randn(5,5)

array([[ 0.51888963, -0.23855565,  1.13708281,  0.8596005 ,  0.10296239],
       [ 0.1902263 , -0.6427366 , -0.61827071,  0.51004622, -0.36097923],
       [-0.10909595,  2.27669882, -0.53040767, -0.86341601, -1.09029568],
       [ 0.31916526,  0.43588995, -0.54600588,  0.60332536,  0.08447836],
       [ 0.61158122,  0.06311748,  1.44128726, -1.14690063, -0.09701317]])

In [36]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [40]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [38]:
ranarr

array([23,  3, 43,  3,  2, 20, 27, 27,  5, 19])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [46]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576],
      dtype=int32)

In [47]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [48]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [54]:
np.min(arr), np.max(arr)

(0, 24)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])